export const data = [
	{
		title: 'Влажность',
		icon: './public/icons/humidity.svg',
		iconMedia: './public/icons/media/humidity--media.svg',
		value: '75 %',
		minParams: '0%',
		maxParams: '100%',
		range: true,
		humidity: true,
	},
	{
		title: 'Давление',
		icon: './public/icons/barometr.svg',
		iconMedia: './public/icons/media/barometr--media.svg',
		value: '761',
		param: 'Повышенное',
		range: true,
		humidity: false,
		pressure: true,
	},
	{
		title: 'Видимость',
		icon: './public/icons/visibility.svg',
		iconMedia: './public/icons/media/visibility--media.svg',
		value: '28 км',
		param: 'Нормальная',
		range: true,
		humidity: false,
	},
	{
		title: 'Рассвет',
		icon: './public/icons/sunrise.svg',
		iconMedia: './public/icons/media/sunrise--media.svg',
		value: '8:42',
		param: 'Прошло: ',
		time: '02:47',
		range: false,
		humidity: false,
	},
	{
		title: 'Закат',
		icon: './public/icons/sunset.svg',
		iconMedia: './public/icons/media/sunset--media.svg',
		value: '16:37',
		param: 'Осталось: ',
		time: '05:08',
		range: false,
		humidity: false,
	},
	{
		title: 'Сила ветра',
		icon: './public/icons/direction.svg',
		iconMedia: './public/icons/media/direction--media.svg',
		value: '2 м/с',
		param: 'Северо-западный',
		range: false,
		humidity: false,
	},
]

export const dataForecast = [
	{
		time: '12:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-7°',
		for24: true,
	},
	{
		time: '15:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-5°',
		for24: true,
	},
	{
		time: '18:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-7°',
		for24: true,
	},
	{
		time: '21:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-9°',
		for24: true,
	},
	{
		time: '00:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-11°',
		for24: true,
	},
	{
		time: '03:00',
		icon: './public/icons/clouds_slide.svg',
		temp: '-13°',
		for24: true,
	},
	{
		time: 'Вс, 07 янв.',
		icon: './public/icons/clouds_sun.svg',
		iconMedia: './public/icons/media/clouds_sun--media.svg',
		temp: 'от -17° до -11°',
		for5: true,
	},
	{
		time: 'Пн, 08 янв.',
		icon: './public/icons/clouds_sun.svg',
		iconMedia: './public/icons/media/clouds_sun--media.svg',
		temp: 'от -16° до -8°',
		for5: true,
	},
	{
		time: 'Вт, 09 янв.',
		icon: './public/icons/clouds_slide.svg',
		iconMedia: './public/icons/media/clouds_slide--media.svg',
		temp: 'от -8° до -2°',
		for5: true,
	},
	{
		time: 'Вт, 10 янв.',
		icon: './public/icons/clouds_slide.svg',
		iconMedia: './public/icons/media/clouds_slide--media.svg',
		temp: 'от -2° до 1°',
		for5: true,
	},
	{
		time: 'Вт, 11 янв.',
		icon: './public/icons/clouds_slide.svg',
		iconMedia: './public/icons/media/clouds_slide--media.svg',
		temp: 'от -5° до -2°',
		for5: true,
	},
]
